name: 'Release Repo'
description: 'Publish a release to an external release repo'
inputs:
  regex:
    description: Regex to match on the name of the files to be downloaded
    required: false
    default: '.*'
  dir:
    description: Directory to download the files into. Defaults to a temp directory.
    required: false
  token:
    description: The GitHub token used access the release
    required: true
outputs:
  paths:
    description: 'A newline seperated list of paths to all the downloaded assets'
runs:
  using: 'node12'
  main: 'main.js'
